### PR TITLE
Fixes #12: Add ability to output markdown

### LINKED ISSUE #12: Ability to output mardown
- [x] add option to output to mardown
- [x] mardown should have the same information/content as html version
- [ ] rename repo? (`aml2doc`?)

### PR DESCRIPTION
**Pull request by postatum**
Fixes #12

Try it out with a new option `--syntax`:
```
npm run aml2doc -- ./outdir --indir=./test_data --syntax=md
```
We still need to rename the repo after this PR is merged.

---
I've fixed this issue by simply declaring a second set of templates specifically for Markdown.

While working on it, I've considered few other options:
1. Convert HTML->Markdown. This didn't work out because I've only found few decent converters (`turndown`, `showdown`) and none of them properly handled our html structure (tables, navigation block, etc.).
2. Convert Markdown->HTML. I decided to not follow this path because if we had templates in md, rendered them and then converted to html, it would break multiple things: css classes/ids, using custom css files.

Choosing either of these options would have added unnecessary complexity to the code (to make out layout with those libs) and increased number of bugs in the future. On the other hand, I think keeping templates up to date is straightforward and add no code complexity.

### CODE REVIEW

**Comment by postatum** [comment]
This PR will need to be update to display primary, secondary and index links in generated Markdown after this issue is fixed https://github.com/aml-org/aml2html/issues/19.

**Comment by antoniogarrote** [comment]
I will rebase this during this week

**Comment by postatum** [comment]
Will close this PR so it doesn't confuse anyone. The issue needs to be addressed more (https://github.com/aml-org/aml2html/issues/12#issuecomment-571559738)

**Comment by postatum** [comment]
I've resolved merge conflicts with `master`, added links supports to md and tests.

Work in this PR is complete and ready to be reviewed.

**Comment by postatum** [comment]
Closing in favour of #25

**Pull request closed without merging**
